### ISSUE TITLE
Upcoming podcast events to add

### ISSUE THREAD

**Issue by Nevraeka** [mateusortiz/webcompomponents-weekly#11]
### The Web Platform Podcast

Live YouTube Hangout on Air events with audio podcast available within 24 hrs after live broadcast on iTunes, Stitcher, & mp3 on the web. These are the upcoming Web Component ones so far
- **[CANCELLED] 44: Updating to Bosonic 2.0**  [Google Hangout on Air Event](https://plus.google.com/u/0/events/ciavi44g2u30upf8lcge2auvlv0) on May 19th 12:30 PM EST
- **[RESCHEDULING] 45: The latest on X-Tag** [Google Hangout on Air Event](https://plus.google.com/u/0/b/106965203807974584370/events/cpmdoori6cg12458h5mqd4vsr7c?authkey=COmE68TJu5mG3QE) on May 25th 12:30 PM EST
- **46: Polymer 1.0 Updates** [Google Hangout on Air Event](https://plus.google.com/u/0/events/cnd2ivdfsn8j73hrd4cqgv9l704) on June 2nd 12:30 PM EST
- **48: Web Accessibility in Polymer** [Google Hangout on Air Event](https://plus.google.com/u/0/events/c1b9tio40dusjo0gaqog6vircdk) on June 18th 12:30 PM EST

**Comment by mateusortiz** [comment]
Thanks @Nevraeka, very cool, I will add in the next weekly

**Comment by mateusortiz** [comment]
In the next weekly I'll add a section dedicated to podcasts, Ok @Nevraeka?

**Comment by Nevraeka** [comment]
I have one on The Strand Library & Supersonic in the works as well but no details yet

**Comment by Nevraeka** [comment]
Moved to Campaign issue #15
