### ISSUE TITLE
[content] Add consolidated Web Components feedback from Apple & Microsoft

### ISSUE THREAD

**Issue by Nevraeka** [mateusortiz/webcompomponents-weekly#13]
https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0263.html
https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0225.html

**Comment by danguilherme** [comment]
Didn't read them yet, but can't we add the one from Mozilla too? https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0052.html

**Comment by Nevraeka** [comment]
:+1: thanks @danguilherme

**Comment by mateusortiz** [comment]
Thanks @Nevraeka and @danguilherme I added the weekly

**Comment by mateusortiz** [comment]
Added to the weekly, will be sent tomorrow at 10:00am :clap:
