### ISSUE TITLE
Campaign 24 - 23/09/2015

### ISSUE THREAD

**Issue by Nevraeka** [mateusortiz/webcompomponents-weekly#32]
The weekly will be sent day 23/09/2015 :mailbox:

Help Web Components Weekly posting your tip, article, links, demos, news or suggestions here in the comments of this issue.
Throughout the week we debating and joining the best links that will be inserted in the next Weekly.

**Comment by Nevraeka** [comment]
F2F Browser Vendor & W3C WebApps group meeting for Shadow DOM Styles - [https://www.w3.org/wiki/Webapps/WebComponentsSeptember2015Meeting](https://www.w3.org/wiki/Webapps/WebComponentsSeptember2015Meeting)

**Comment by Nevraeka** [comment]
Publishing Web Components talk from DevFest DC 2015
[Slides](https://docs.google.com/presentation/d/1MMCMs1bH3H-QBwLQgevTJOW7mzUpQ8YygJ09HMm_5N0/edit?usp=sharing)
[Video (44 min)](https://www.youtube.com/watch?v=2FGTvxPEwR0)

**Comment by Nevraeka** [comment]
### Shadow DOM v1 Browser Vendor Updates
- [Updated Spec Reference](http://w3c.github.io/webcomponents/spec/shadow/)
- [Chromium.org Google Mailing Group Summary](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/Ez2cuT0KmQo/eUpSsU-uAgAJ)
- [WebKit Intent to Implement](https://lists.webkit.org/pipermail/webkit-dev/2015-September/027661.html)
- [Edge](https://dev.modern.ie/platform/status/shadowdom/)

#### Public Bugs
- [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1205323)
- [Chrome](https://code.google.com/p/chromium/issues/detail?id=531990) 
- [WebKit Bug](https://bugs.webkit.org/show_bug.cgi?id=148695)

**Comment by Nevraeka** [comment]
@JanMiksovsky , creator of [Component.kitchen](http://component.kitchen) and The Web Components [Gold Repository](https://github.com/webcomponents/gold-standard), has started working on a new set of Polymer Components called [Basic Web Components](https://github.com/basic-web-components). Visit [the contributions section](https://github.com/basic-web-components/basic-web-components#contributing) for details on how you can help evolve these components

**Comment by JanMiksovsky** [comment]
Thanks for helping us spread the word!

Minor edits: the checklist is called the Gold Standard, not the Gold Repository. Also, it's probably better to link directly to the [wiki](https://github.com/webcomponents/gold-standard/wiki), since that's where the interesting content is.

**Comment by mateusortiz** [comment]
sorry last Wednesday I could not do the weekly :confused:, but the weekly of tomorrow is ready and full of links.

Thanks @Nevraeka @JanMiksovsky
