### ISSUE TITLE
WebKit adding ShadowDOM support

### ISSUE THREAD

**Issue by sebdeckers** [mateusortiz/webcompomponents-weekly#36]
Seems like there is a lot of activity coming from WebKit developers around the new ShadowDOM support. Can't find it in the WebKit nightly build yet though. Worth a mention in the weekly newsletter as a heads up? Let's give these webcomponent heroes some support. :rocket:

https://twitter.com/webkit/status/648546431771344896

> Scoped styling for shadow DOM has been implemented. Lots of progress on shadow DOM last week.

https://twitter.com/anttikoivisto/status/653268996960202752

> WebKit is now using the modern Shadow DOM API internally

https://twitter.com/anttikoivisto/status/653269756481548288

> The last vestiges of the V0 Shadow DOM are gone too

https://twitter.com/ryosukeniwa/status/654901943236562944

> Alright, #ShadowDOM v1 API is done.  Time to start prototyping #CustomElements in #WebKit before #2015TPAC.

**Comment by sebdeckers** [comment]
Mentioned in [Web Components Weekly #28](http://us10.campaign-archive2.com/?u=6cd727a9a0da64b4003caa164&id=695e446a8d&e=d0709a1382).

**Comment by mateusortiz** [comment]
Thanks @cbas :clap:
