### ISSUE TITLE
SnapDrop

### ISSUE THREAD

**Issue by RobinLinus** [mateusortiz/webcompomponents-weekly#40]
A Polymer clone of Apple's Airdrop https://snapdrop.net
It is a progressive Web App that uses WebRTC for instant p2p file-sharing. 
Feedback very appreciated!

**Comment by mateusortiz** [comment]
Thanks @capira12, add on weekly! :christmas_tree:

**Comment by RobinLinus** [comment]
Thanks a lot! BTW: I open sourced it :-) https://github.com/capira12/snapdrop
